"""empty message

Revision ID: 00b5615b3474
Revises: 40f1c07e812a
Create Date: 2022-03-29 00:58:19.728502

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '00b5615b3474'
down_revision = '40f1c07e812a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('task', table_name='todo')
    op.drop_index('task_2', table_name='todo')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('task_2', 'todo', ['task'], unique=False)
    op.create_index('task', 'todo', ['task'], unique=False)
    # ### end Alembic commands ###
